### ISSUE TITLE
Some ERC721s do not revert when a transfer fails

### ISSUE THREAD

**Issue by LiRiu** [decentraland/marketplace-contracts#64]
About contract [Marketplace](https://github.com/decentraland/marketplace-contracts/blob/32d17b06b1f5df0abe376fb93be12258f6707a8a/contracts/marketplace/Marketplace.sol#L302)

in `createOrder` function, the nftaddress not be checked implement or must in the nft_registry_whitelist. 
so the attacker can create an sell_order with a malicious nft_registry which safeTransferFrom return Failed.

### Impact
when victim invoke the executeOrder function: 

he will pay acceptToken but won't get the NFT(assetId), and the transaction not revert but success cause of there's no require success before nftRegistry.safeTransferFrom(order.seller, sender, assetId);

### Recommend
check if the owner of assetId is buyer, after the nftRegistry.safeTransferFrom

**Comment by LiRiu** [comment]
I originally tried to write a POC on the kovan, but the setup of environment  and the unstable remix-ide made me a little bit painful.
so...uhhhh.....i really admire you bring a wonderful project to the world... and uhhhh....i decided to shares my confusion asap...( although there's no POC )

**Comment by nachomazzara** [comment]
Hi @LiRiu, thanks for your comments.

The users need to trust the NFT they are about to buy by design. If we also check the `ownerOf`, the NFT smart contract can also always return `true` making it bypassable like:

```solidity
function ownerOf(address _address) returns (bool) {
    return true;
}
```

Also, implementing a whitelist generates a lot of manual work for admins. That is why we make the previous assumption and build the smart contract as it is.

**Comment by LiRiu** [comment]
Thank you, i see
